name: Copy ROM to Repository

on:
  push:
    branches:
      - '**'  # Triggers on all branches
  pull_request:
    branches:
      - '**'

jobs:
  copy-rom:
    runs-on: ubuntu-latest
    
    # Use your private container image
    container:
      image: ghcr.io/celophi/slus-01013:v1.1
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: lom
          submodules: recursive
          ref: ${{ github.head_ref || github.ref_name }}
      
      - name: Copy ROM file
        working-directory: ${{ github.workspace }}/lom
        run: |
          cp /rom/SLUS_010.13 disc/

      - name: Install Python dependencies
        working-directory: ${{ github.workspace }}/lom
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run splat
        working-directory: ${{ github.workspace }}/lom
        run: |
          splat split config/SLUS_010.13.yaml --make-full-disasm-for-code

      - name: Generate objdiff config
        working-directory: ${{ github.workspace }}/lom
        run: python3 tools/objdiff/generate_objdiff_config.py

      - name: Build target objects
        working-directory: ${{ github.workspace }}/lom
        run: make clean && make objdiff-objects
        
      - name: Generate objdiff report
        working-directory: ${{ github.workspace }}/lom
        run: |
          chmod +x ./tools/objdiff/objdiff-cli-linux-x86_64
          ./tools/objdiff/objdiff-cli-linux-x86_64 report generate -o build/report.json

      - name: Upload progress report
        working-directory: ${{ github.workspace }}/lom
        uses: actions/upload-artifact@v4
        with:
          name: SLUS_010.13_report
          path: build/report.json