name: Copy ROM to Repository

on:
  push:
    branches:
      - '**'  # Triggers on all branches
  pull_request:
    branches:
      - '**'

jobs:
  copy-rom:
    runs-on: ubuntu-latest
    
    # Use your private container image
    container:
      image: ghcr.io/celophi/slus-01013:v1.1
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: lom
          submodules: recursive
          ref: ${{ github.head_ref || github.ref_name }}
      
      - name: Copy ROM file
        working-directory: ${{ github.workspace }}/lom
        run: |
          cp /rom/SLUS_010.13 disc/

      - name: Install Python dependencies
        working-directory: ${{ github.workspace }}/lom
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run splat
        working-directory: ${{ github.workspace }}/lom
        run: |
          splat split config/SLUS_010.13.yaml --make-full-disasm-for-code